name: Build Release Zip

on: push

permissions:
  contents: write

jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create zip
        run: |
          git archive --format=zip --output=aseprite-spritesheet-importer.zip HEAD

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: aseprite-spritesheet-importer.zip
          generate_release_notes: true
